// set numbre from the keyboard to text area....
let num = document.getElementsByClassName('num')//variable declaration.....
var res = document.getElementById("valu")//variable declaration.....
for(let i = 0;i<num.length;i++){
    num[i].addEventListener('click',function(){
    if(test.value == 1){
        res.value ="";    
        test.value = 0
    }
    res.value+=num[i].value;
        
    })
}
var test = document.getElementById("test")

// add operation to the text area....
let op = document.getElementsByClassName('ope')//variable declaration.....
var res = document.getElementById("valu")//variable declaration.....
for(let i = 0;i<op.length;i++){
    op[i].addEventListener('click',function(){
        let k =res.value += op[i].value;
        
    })
    
}
//The result of the calculation......
let equals = document.getElementById("equals");//equal variable declaration.....
//add an event for the equal variable.....
equals.addEventListener('click', function () {
    //Transfer math operations from string form to math form using evaluate function.......
    res.value = eval(res.value);
    test.value = 1
});
// Delete an item from the text area........
let del = document.getElementById("delete")//variable declaration.....
var res = document.getElementById("valu")//variable declaration.....
del.addEventListener('click',function(){
    res.value ="";

})
